# ----------------------------
# Makefile Options
# ----------------------------

NAME = PiConCtl
ARCHIVED = NO
DESCRIPTION = "Pi console keyboard"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -O3
CXXFLAGS = -Wall -Wextra -O3
# ----------------------------

include $(shell cedev-config --makefile)
